stages:
  # - cluster-setup
  # - portal-setup
  - cypress-setup
  - basic-auth-tests
  # - gui-tests
  # - e2e-metrics
  # - portal-cleanup
  # - cluster-cleanup

variables:
  npm_config_cache: "$CI_PROJECT_DIR/.npm"
  CYPRESS_CACHE_FOLDER: "$CI_PROJECT_DIR/cache/Cypress"

cache: &global_cache
  key: ${CI_PROJECT_NAME}-${CI_COMMIT_REF_SLUG}
  paths:
    - .npm
    - cache/Cypress
    - Cypress/node_modules

# EKS-Setup:
#   stage: cluster-setup
#   tags:
#     - kubera-litmus
#   script:
#     - chmod 755 build/eks/1-cluster-setup/setup
#     - ./build/eks/1-cluster-setup/setup
#   artifacts:
#     when: always
#     paths:
#       - .kube/
#   cache: {}

# Portal-Setup:
#   when: always
#   stage: portal-setup
#   tags: 
#     - kubera-litmus
#   script:
#     - make install-portal
#   artifacts:
#     when: always
#     paths:
#       - .kube/
#       - url.txt
#   cache: {}

Cypress-Setup:
  when: always
  stage: cypress-setup
  image: jonsy13/cypress-small:buster-slim
  tags:
    - kubera-litmus
  script:
    - make cypress-setup

TCID-VMWx-Portal-GUI-Auth:
  when: always
  stage: basic-auth-tests
  # dependencies:
  #   - Portal-Setup
  image:
    name: jonsy13/cypress-small:buster-slim
  tags:
    - kubera-litmus
  script:
    # - source url.txt
    # - echo $URL
    - URL="http://aee47567955734778a7ec5e16632c1b1-1037557215.us-east-2.elb.amazonaws.com:9091" make pre-test-setup
  artifacts:
    when: always
    paths:
      - Cypress/cypress/screenshots
  cache:
    <<: *global_cache
    policy: pull

# .cypress-e2e:
#   when: always
#   stage: gui-tests
#   dependencies:
#     - Portal-Setup
#   image:
#     name: jonsy13/cypress:buster-slim
#   tags:
#     - kubera-litmus
#   artifacts:
#     when: always
#     paths:
#       - Cypress/cypress/screenshots
#   cache:
#     <<: *global_cache
#     policy: pull

# TCID-VMWx-Portal-GUI-Routes:
#   extends: .cypress-e2e
#   script:
#     - source url.txt
#     - URL=$URL make routes-check

# TCID-VMWx-portal-GUI-ScheduleWorkflow:
#   extends: .cypress-e2e
#   script: 
#     - source url.txt
#     -  URL=$URL make create-workflow-check

# TCID-VMWx-Portal-GUI-CommunityData:
#   extends: .cypress-e2e
#   script: 
#     - source url.txt
#     -  URL=$URL make community-page-check

# TCID-VMWx-Portal-GUI-AccountSettings:
#   extends: .cypress-e2e
#   script: 
#     - source url.txt
#     - URL=$URL make account-settings-check

# TCID-VMWx-Portal-GUI-BrowseWorkflows:
#   extends: .cypress-e2e
#   script: 
#     - source url.txt
#     -  URL=$URL make browse-workflow-check

# e2e-metric:
#   when: always
#   stage: e2e-metrics
#   tags: 
#     - kubera-litmus
#   script:
#     - make e2e-metrics
#   artifacts:
#     when: always
#     paths:
#       - .kube/
#   cache: {}

# portal-cleanup:
#   when: always
#   stage: portal-cleanup
#   tags: 
#     - kubera-litmus
#   script:
#     - make uninstall-portal
#   artifacts:
#     when: always
#     paths:
#       - .kube/
#   cache: {}
    
# EKS-Cleanup:
#   when: always
#   stage: cluster-cleanup
#   tags:
#     - kubera-litmus
#   script:
#     - chmod 755 build/eks/2-cluster-cleanup/cleanup
#     - ./build/eks/2-cluster-cleanup/cleanup
#   artifacts:
#     when: always
#     paths:
#       - .kube/
#   cache: {}
